from hello import car
car_1 = car("benz","ferrari","2023","red")
car_2 = car("toyoya", "camery", "2022", "white")
print(car_1.make)
print(car_1.color)
print(car_1.model)
print(car_1.year)
car_1. drive()
car_1. stop()
print(car_2.make)
print(car_2.color)
print(car_2.model)
print(car_2.year)
car_2. drive()
car_2. stop()
